// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCC_System_Data;

namespace TCC_System_Data.Migrations
{
    [DbContext(typeof(TCC_Context))]
    partial class TCC_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("TCC_System_Domain.Management.Claims", b =>
                {
                    b.Property<int>("ClaimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeClaim")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordCreatedBy")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<DateTime?>("RecordCreationDate")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("RecordUpdateDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("RecordUpdatedBy")
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("ClaimID");

                    b.ToTable("AUTH_Claims");
                });

            modelBuilder.Entity("TCC_System_Domain.Management.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordCreatedBy")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<DateTime?>("RecordCreationDate")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("RecordUpdateDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("RecordUpdatedBy")
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("Id");

                    b.ToTable("AUTH_Users");
                });

            modelBuilder.Entity("TCC_System_Domain.Management.UserClaims", b =>
                {
                    b.Property<int>("UsuarioID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClaimID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordCreatedBy")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<DateTime?>("RecordCreationDate")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("RecordUpdateDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("RecordUpdatedBy")
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("UsuarioID", "ClaimID");

                    b.HasIndex("ClaimID");

                    b.ToTable("AUTH_UserClaims");
                });

            modelBuilder.Entity("TCC_System_Domain.Management.UserClaims", b =>
                {
                    b.HasOne("TCC_System_Domain.Management.Claims", "Claims")
                        .WithMany("ClaimUsers")
                        .HasForeignKey("ClaimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCC_System_Domain.Management.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
